# Максимальный предел гаммы
max-gamma = 150

# ФАЗА 1: Утро и День (Работа и высокая активность)
profile {
    time = 06:00
    temperature = 5500
    gamma = 0.95
}

# ФАЗА 2: Конец рабочего дня (Подготовка к вечеру)
profile {
    time = 18:00
    temperature = 5500
    gamma = 0.95
}

# ФАЗА 3: Вечер (Плавное снижение синего спектра)
profile {
    time = 20:00
    temperature = 4500
    gamma = 0.90
}

# ФАЗА 4: Ночь (Максимальная защита глаз перед сном)
profile {
    time = 21:00
    temperature = 4000
    gamma = 0.85
}
